### ISSUE TITLE
Add a Roadmap

### ISSUE THREAD

**Issue by leossb36** [deeplearningunb/stonks#47]
**Is your feature request related to a problem? Please describe.**

We need a roadmap to set versions and functions to our project

**Checklist**
- [x] The issue has a meaningful name.
- [x] The issue has a meaningful description.
- [ ] The issue has screenshots when needed.
- [x] The issue has labels.
